# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.5.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - npm install -g yarn
          - yarn
          - yarn run lint
          - yarn run test